### ISSUE TITLE
Empty columns in tdms files

### ISSUE THREAD

**Issue by phidahl** [ZellMechanik-Dresden/dclab#1]
If there is one empty column in a tdms files ShapeOut gives an error message ("A "None Type" object has no attribute "shape".)
Background is that in fRT-DC data files these empty columns can be there if not all available fluorescence channels are used.

**Comment by paulmueller** [comment]
Could you post a detailed error message?
This is probably easy to fix once we know which lines we are talking about.

**Comment by phidahl** [comment]
I think its easy, the tdmsfile.object(...).data objects are None if empty.

The message is:
..
File: ...shapeout.tlabwrap", line 47, in __init__
File: ...dclab", line 409, in __init__ AttributeError: "None Type" object has no attribute "shape"

I hope this helps. Why can't I copy paste error messages in windows? :(
