### ISSUE TITLE
AncillaryFeature as a Plug-In

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/dclab#105]
This is part 1 of #98, split out so it is easier to track.

Create a plug-in interface using something like [AncillaryFeature](https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/master/dclab/rtdc_dataset/ancillaries/ancillary_feature.py). The user creates a separate plug-in (Python script) which can be (automatically) loaded at runtime. The upside here would be that users might also be able to use such plug-ins in Shape-Out at some point. And, if they are based on AcnillaryFeature, they can also be incorporated at some point in dclab.

**Comment by PinkShnack** [comment]
Here is a sketch of what this might look like (could be completely different to what you had in mind @paulmueller).

    (dclab) RTDCBase
        Checks for any TempUserFeature, adds it as a feature (like with Ancillary)
                  |
                  |
    (dclab) TempUserFeature class
        Contains methods that can be overridden by child class in Script
                  |
                  |
    (ext. Script) ExamplePluginCalculateFakeViscosity(TempUserFeature) class
        What the user interacts with.
        The user defines what is needed to calculate the new feature, and how to calculate it (like with Ancillary)


For this we would need:

- A new module in rtdc_dataset called `temp_user_feature.py`. 
- New checks within RTDCBase that look for these `TempUserFeature`
- A `TempUserFeature` class that is instantiated with similar arguments as in `AncillaryFeature`. It should also contain several methods that can be overridden via the user-written script e.g., `calculate_feature` which would return the feature value.
- A user plugin script with a class that inherits from `TempUserFeature` and overrides the `TempUserFeature` methods.
- For automatic loading, would it be easiest for the user to be able to either specify the path containing the plugins, place them with the data location, or have them pulled from some online repo? Or all three?

I thought to have the `TempUserFeature` functionality within the `AncillaryFeature` class, but that would be too cluttered probably.

Let me know your thoughts. :)

**Comment by paulmueller** [comment]
Thanks, it isn't at all clear to me how to approach this. But here are a few thoughts:

- It would probably be best if this `TempUserFeature` was a subclass of `AncillaryFeature` (or they share the same base class if that is not possible).
- Now that I am thinking of it, I think we should first address #104 to avoid major refactoring if we do this here first.
- I think the name `TempUserFeature` is too close to `temporary_feature` in #98. I would prefer `PlugInFeature` or something similar.
- General remark: The idea is that if such a user-defined feature proves to be useful, then we can just copy the code and turn it into a "real" `AncillaryFeature`.
- In the original post I wrote that the user-defined plug-ins could be loaded **automatically** at run-time. I don't agree with me anymore. I think the user should explicitly load an ancillary plug-in feature at the beginning of his script. We can still automate these things for Shape-Out, but it goes too far for a basic library. So I would remove the last point from your list.

Now it's a little more clear to me :smile_cat:

**Comment by PinkShnack** [comment]
> Now that I am thinking of it, I think we should first address #104 to avoid major refactoring if we do this here first.

I will have a look at this now!


> * General remark: The idea is that if such a user-defined feature proves to be useful, then we can just copy the code and turn it into a "real" `AncillaryFeature`.

I thought as much. Good idea with making the `PlugInFeature` class a subclass of `AncillaryFeature`. That will probably make this "copying" of code much smoother.

Also, see my edits in the first comment. I have a new possible layout based on your comments.

**Comment by paulmueller** [comment]
I think we should first discuss how the plugin user interface should look like in the end. I would start with something similar to AncillaryFeature (e.g. https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/master/dclab/rtdc_dataset/ancillaries/af_basic.py).


## General Remarks
- All tests that were implemented for the temporary features should also be implemented for the PluginFeatures. This should already cover a lot of use-cases.
- The `PluginFeature` class always has to keep track which feature was loaded so it can unload it later-on.
- It should also keep track of which datasets it modified so that it can remove the data from those datasets. Users could get the idea of loading different plugins for the same feature in series (e.g. different ways of computing the `smoothness` of an image). If a feature is already defined, then AncillaryFeature will not attempt to recompute it. Maybe it would make sense to implement this for temporary features as well.
- We have to take into account #104, i.e. support the computation of multiple features from only one method.

## Simple approach

```python
"""This is an example plugin"""
def compute_my_feature(rtdc_ds):
    """The function that does the heavy-lifting"""
    [...]
    return feature_data

# register the plugin feature
PluginFeature(feature_name="my_feature",
              method=compute_my_feature,
              req_features=["area_cvx", "area_msd"],
              priority=1,)
```
Remarks:
- The plugin file cannot be easily parsed (to see which features the plugin provides before actually loading it).
- This does not cover #104


## "Flat" approach
```python
"""This is an example plugin"""

def compute_my_features(self, rtdc_ds):
    """The function that does the heavy-lifting"""
    [...]
    # returns a dictionary-like object
    return {"feature_1": data1, "feature_2": data2}

info = {
    "method": compute_my_features,
    "description": "a description",
    "feature names": ["feature_1", "feature_2"],
    "feature labels": ["Feature label 1", "Feature label 2"],
    "features required": ["area_cvx", "area_msd"],
    "config required": [...],
    "method check required": other_method,
    "priority": 1,
    "version": "0.1.1",
}
```
Remarks:
- This plugin can just be imported (see Shape-Link plugin) and all information is in `info`.
- This would cover #104
- This is easy to comprehend
