### ISSUE TITLE
Add new metadata key and functions for "baseline offset"

### ISSUE THREAD

**Issue by maxschloegel** [ZELLMECHANIK-DRESDEN/dclab#107]
This issue is a prerequisite for [ZELLMECHANIK-DRESDEN/DCKit#11](https://github.com/ZELLMECHANIK-DRESDEN/DCKit/issues/11).
As described there, we want to be able to compute possible baseline offsets for all fluorescence traces. This in turn can be used to correct fl?_max values.
This prerequisite includes:
- Add metadata-keys for "baseline ? offset"
- Add ancillary functions to compute baseline offset for given traces

**Comment by paulmueller** [comment]
In which submodule should we put the function to determine the baseline offset? Initially I thought this should be in DCKit, but it might be useful to have this well-documented in dclab.

**Comment by maxschloegel** [comment]
I am not sure either. Currently I would put `compute_offset()` into `rtdc_dataset/ancillaries/af_basic.py`, and adjust the `fl?_max`-values directly in DCKit.
On the other hand:  I was playing around on how to get the minimum trace-value. Since the trace-values are roughly an array of size `[100000, 1000], we thought about using only the traces of the 100 lowest peaks to cut down the computation time.
But when I was applying this to a dataset, the lowest trace value was not in those 100 traces, not even the traces with 1000 lowest peaks. Above 1000 lowest peak samples the computation time and rearranging of the indices etc. gets quite long by itself. So I timed the computation of `np.min` on an array of above mentioned size with a similar value range as the actual traces and the mean computation time is about 0.1 seconds. Is that feasible?
To get back to the question, where to put the function: If this is feasible and we simply use `np.min` on the traces, then maybe implementing an actual function is unnecessary.

**Comment by paulmueller** [comment]
I think such a function does not really belong with `ancillaries`. This qualifies more for a `repair` or `fix` submodule. 0.1 seconds is really fine though from the user's perspective. So I would just go with `np.min` then.

Implement the "heavy-lifting" logic in DCKit and just add the new configuration values in `dclab.definitions` to close this issue here.
