### ISSUE TITLE
Implement `.shape` for non-scalar features

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/dclab#117]
This is a convenience method. Ideally, one would be able to do `rtdc_ds["mask"].shape` independent of the subclass (hierarchy child, HDF5, tdms). Currently, this only works for the HDF5 format.

**Comment by PinkShnack** [comment]
First question: What do we want as shape?
Normally shape is (y, x) or (z, y, x), as in Numpy. This isn't consistent at the moment.
For example, I guess `ds["Image"].shape` should return (z, y, x), whereas `ds["Image"][0].shape` will return (y, x).

# Contour

### hdf5
I guess contour is not included in this enhancement, as the length of each contour is not the same. This I guess is why (with hdf5) `ds["contour"].shape` results in `AttributeError: 'LazyContourList' object has no attribute 'shape'`.

### tdms
Does this means that the `ContourColumn.shape` attribute is nonsense? It grabs its shape from the `"image"`:

```
if "image" in rtdc_dataset:
    self.shape = rtdc_dataset["image"].shape
```

### hierarchy child
todo

# Image
### hdf5
Seems to work fine, gives (z, y, x)

### tdms
`.shape` and `._shape` yield (y, x)

### hierarchy child
todo

# Mask
### hdf5
Seems to work fine, gives (z, y, x)

### tdms
`._shape` yields (y, x)
`.shape` is not an attribute

### hierarchy child
todo

# Traces

Need to find a dataset

**Comment by paulmueller** [comment]
Thanks for looking into this.

Regarding your question: Shape should be `(len(dataset), image_shape_0, image_shape_1)`.

For *contour* I guess it could make sense to return `(len(dataset), np.nan, 2)` - in any case the current implementation for the tdms format is definitely a bug. I think I have no problem with removing `shape` for contours.

I think this issue should be rolled out in two phases to make sure there are no breaking changes, because some code might rely on the fact that `len(ds["image"].shape) == 2`.

Phase 1:
- Add deprecation warnings to the relevant positions in the code where `len(shape)` would be 3 instead of 2.
- Implement `shape` wherever it is not implemented

Phase 2:
- Make `shape` consistent everywhere.

**Comment by PinkShnack** [comment]
> For _contour_ I guess it could make sense to return `(len(dataset), np.nan, 2)` - in any case the current implementation for the tdms format is definitely a bug. I think I have no problem with removing `shape` for contours.

I think it would be okay to have `np.nan` as the y axis length. I think, if `ds["contour"].shape` is called, it would be helpful to have a warning/explanation of why `np.nan` is appearing in a shape attribute by design.

Thanks for the reply, it's quite clear to me now!

**Comment by PinkShnack** [comment]
### Possible `.shape` bug

I added this `.shape` check to `AncillaryFeature.compute` in #113:

```python
        for key in data_dict:
            dfn.check_feature_shape(self.feature_name, data_dict[key])
```

where `dfn.check_feature_shape` is the same check as that done for temporary features:

```python

def check_feature_shape(feature, data):
    data = np.array(data)
    if len(data.shape) == 1 and not scalar_feature_exists(feature):
        raise ValueError("Feature '{}' is not a scalar feature, but a "
                         "1D array was given for `data`!".format(feature))
    elif len(data.shape) != 1 and scalar_feature_exists(feature):
        raise ValueError("Feature '{}' is a scalar feature, but the `data` "
                         "array is not 1D!".format(feature))
```

Where the `contour` feature is being computed, some tests fail. The failure is due to the fact that `contour` is not a scalar, but `contour.shape == 1`, which is wrong. This bug should be fixed here. 


### Error Traceback
Here is an example traceback, notice that the contour data is an array of a list.:

```python
def check_feature_shape(feature, data):
    data = np.array(data)
    # bug: reloaded contour is of the form: array([array([[1,2],[...]...])])
    # which means len(data.shape) == 1.
    if feature == "contour" and len(data.shape) == 1:
        pass
    elif len(data.shape) == 1 and not scalar_feature_exists(feature):
        ...
```

Here is a standard traceback:

```bash
    def test_split_traces():
        path_in = retrieve_data("rtdc_data_hdf5_rtfdc.zip")
>       paths = cli.split(path_in=path_in, split_events=3, ret_out_paths=True)

tests\test_cli.py:243:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
dclab\cli.py:517: in split
    skip_empty_image_events(ds, initial=skip_initial_empty_image,
dclab\cli.py:423: in skip_empty_image_events
    or ("contour" in ds and np.all(ds["contour"][0] == 0))
dclab\rtdc_dataset\core.py:110: in __getitem__
    data_dict = ancol[key].compute(self)
dclab\rtdc_dataset\ancillaries\ancillary_feature.py:208: in compute
    dfn.check_feature_shape(self.feature_name, data_dict[key])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

feature = 'contour'
data = array([array([[186,  36],
       [186,  35],
       [186,  34],
       [186,  33],
       [185,  32],
       [185,  31...,  45],
       [107,  44],
       [108,  43],
       [109,  42],
       [109,  41],
       [110,  40]])], dtype=object)

    def check_feature_shape(feature, data):
        data = np.array(data)
        # bug: reloaded contour is of the form: array([array([[1,2],[...]...])])
        # which means len(data.shape) == 1.
        # if feature == "contour" and len(data.shape) == 1:
        #     pass
        if len(data.shape) == 1 and not scalar_feature_exists(feature):
>           raise ValueError("Feature '{}' is not a scalar feature, but a "
E           ValueError: Feature 'contour' is not a scalar feature, but a 1D array was given for `data`!

```

**Comment by paulmueller** [comment]
Note that this should also be implemented for the `RTDC_Dict` and `RTDC_DCOR` formats (all formats).

**Comment by paulmueller** [comment]
TODO

- [x] contour (5183abc also fixes the bug described by @PinkShnack above)
- [ ] image
- [ ] mask
- [ ] trace

**Comment by paulmueller** [comment]
See commits above.

**Comment by PinkShnack** [comment]
Nice!
