### ISSUE TITLE
Can dclab-verify-dataset return a value?

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/dclab#120]
Hi,

I'm trying to include dclab's verify dataset into an automated testing environment. It would be best, if dclab-verify-dataset would return a value to the command line with "sys.exit(value)" indicating if there were errors or not. 

Or am I overseeing something here and this is already implemented?

https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/bf009069fae3aa61ae72f6b4bb0aeed4181a2d9c/dclab/cli.py#L727

**Comment by paulmueller** [comment]
I guess it would make sense to return `1` if the checks failed and `0` otherwise. It should also be possible to specify a flag so that it returns `1` when there are no violations, but when there are warnings.

**Comment by paulmueller** [comment]
This will be available in the next release.

**Comment by phidahl** [comment]
Sorry to reopen this,
I would suggest the following behavior: 
return 1 if there were only warnings
return 2 if there were only violations
return 3 if there were both
return 0 if ok

This would be best, because the file format is under development (meta data fields etc) and additions might be included at different points in time to ShapeIn and dclab.

**Comment by paulmueller** [comment]
Yes, we can implement this.

But: Is it that erally critical for CI runs in Shape-In development? For instance, you could have two CI runs, one with a pinned version of dclab and one with the latest version of dclab (which is allowed to fail). In any case, datasets created with Shape-In should not produce any alerts or violations, so I would treat those equally.

**Comment by phidahl** [comment]
Then let's do it like that. I think testing development versions of ShapeIn won't be the only occasion where knowing if it was a warning of critical might be useful.
And checking the return code for != 0 will still work.

**Comment by paulmueller** [comment]
https://dclab.readthedocs.io/en/latest/sec_cli.html#dclab-verify-dataset
