### ISSUE TITLE
KeyError for Young's modulus computation

### ISSUE THREAD

**Issue by felix-r** [ZELLMECHANIK-DRESDEN/dclab#139]
When I try to compute the Young's modulus from a rtdc file exactly using the example code from the documentation (https://dclab.readthedocs.io/en/stable/sec_av_emodulus.html) I still cannot call `ds['emodulus']` and always get a `KeyError`. I use the following code:

```python
rtdc_file = r'T:\\Data\\RTDC\\20200729_Felix_S03_fullchannel_flowrate_study\\standardRTDC\\M001_data.rtdc'

ds = dclab.new_dataset(rtdc_file)

# Add additional information. We cannot go for (A), because this example
# does not have the temperature feature (`"temp" not in ds`). We go for
# (C), because the beads were measured in a known medium.
ds.config["calculation"]["emodulus lut"] = "LE-2D-FEM-19"
ds.config["calculation"]["emodulus medium"] = ds.config["setup"]["medium"]
ds.config["calculation"]["emodulus temperature"] = 23.0  # a guess

# Plot a few features
ax1 = plt.subplot(121)
ax1.plot(ds["deform"], ds["emodulus"], ".", color="k", markersize=1, alpha=.3)
ax1.set_ylim(0.1, 5)
ax1.set_xlim(0.005, 0.145)
ax1.set_xlabel(dclab.dfn.get_feature_label("deform"))
ax1.set_ylabel(dclab.dfn.get_feature_label("emodulus"))

ax2 = plt.subplot(122)
ax2.plot(ds["area_um"], ds["emodulus"], ".", color="k", markersize=1, alpha=.3)
ax2.set_ylim(0.1, 5)
ax2.set_xlim(30, 120)
ax2.set_xlabel(dclab.dfn.get_feature_label("area_um"))

plt.show()
```

And get the following error:

```python
KeyError                                  Traceback (most recent call last)
<ipython-input-16-c12e07e32286> in <module>
     12 # Plot a few features
     13 ax1 = plt.subplot(121)
---> 14 ax1.plot(ds["deform"], ds["emodulus"], ".", color="k", markersize=1, alpha=.3)
     15 ax1.set_ylim(0.1, 5)
     16 ax1.set_xlim(0.005, 0.145)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\dclab\rtdc_dataset\core.py in __getitem__(self, key)
    112             return data
    113         else:
--> 114             raise KeyError("Feature '{}' does not exist!".format(key))
    115 
    116     def __iter__(self):

KeyError: "Feature 'emodulus' does not exist!"
```

I work with dclab v0.35.4

**Comment by paulmueller** [comment]
Is this the file?: https://dcor.mpl.mpg.de/dataset/2020-07-29_1432_ef738d/resource/4b7d0120-8988-28f6-d0a7-efa367c7b56a

I cannot reproduce this on Linux.

![image](https://user-images.githubusercontent.com/2853022/132379268-cc340723-42e1-4b82-99b3-f3d018db4602.png)

**Comment by felix-r** [comment]
It is the same file. I also tried running the same code by loading the data from dcor and then it works! Same code, initializing the dataset from the rtdc file results in the `KeyError`.

Pretty strange, huh? :D

**Comment by paulmueller** [comment]
So then it might be related to the fact that you are opening the file on a network share? Could you try copying the M001_data.rtdc file to your computer and run the script again?

**Comment by felix-r** [comment]
Copied it to the local drive. Same error.

**Comment by paulmueller** [comment]
So this issue is only present with the original file. I will have a look.

**Comment by paulmueller** [comment]
A workaround is very likely to pipe the file through DCKit.

**Comment by felix-r** [comment]
My current workaround is to use directly the function `emodulus.get_emodulus` from `dclab.features`. But I will try it with DCKit.

**Comment by felix-r** [comment]
Loading them to DCKit revealed the error: The files I want to analyze all got saved as reservoir measurements. Pretty strange because the ROI setting are those for a channel measurement. Is it possible to change this information information somehow in the rtdc-file? Also: How does it work in DCOR then?

**Comment by paulmueller** [comment]
The issue is that the value for ["setup"]: "chip region" is camel-case `"Channel"` instead of lower-case `"channel"` and due to a regression in dclab that does not get converted properly. I will write a fix with proper tests.
