### ISSUE TITLE
Plugin feature documentation never specifies that it should be only one plugin per file

### ISSUE THREAD

**Issue by PinkShnack** [ZELLMECHANIK-DRESDEN/dclab#151]
After discussing plugins with Pierre, we noticed that it is never explicitly stated that there should be only one plugin per `.py` plugin file. We should write this in the docstring and the docs for clarity.

**Comment by paulmueller** [comment]
Actually, it is technically possible, but then all features are computed at once, so probably not very useful.

**Comment by PinkShnack** [comment]
Hmmm, I see that my message is unclear. We can have one `info` metadata dict that describes a function. This function can compute more than one plugin feature. But we should describe that one should only have one `info`  metadata dict per `.py`.
