### ISSUE TITLE
Accessing a slice of non-scalar plugin-features loads the complete array into memory

### ISSUE THREAD

**Issue by maxschloegel** [ZELLMECHANIK-DRESDEN/dclab#162]
When loading a not-scalar plugin-feature and accessing a slice of the previously computed data-array of a rtdc_dataset, loads the complete array into memory. For scalar-features this is not a issue, but when working with very large arrays of non-scalar entries, this fills up the memory and stops the kernel.

This seems to stem from the implementation of the `__getitem__()`-function of the `H5Events`-class: dcml/rtdc_dataset/fmt_hdf5.py#69 .
Only for the innate non-scalar features "image" and "image_bg" is the data loaded as a complete hdf5-dataset.

This problem can be solved in two ways:

1. First load features `contour`, `mask` and `trace` and then for all other features only load the hdf5-dataset.
2. First define for all scalar features and non-scalar features `contour`, `mask` and `trace` how to load the data and all remaining non-scalar features should only load the hdf5-dataset instead of the complete array.

If approach 1 does not work, we will use approach 2.

**Comment by paulmueller** [comment]
I just thought about it. Instead of using `dfn.is_scalar_feature`, you could just check the shape of the dataset. This would be much quicker and also cleaner.
