### ISSUE TITLE
Cannot access datasets from .rtdc files created with dclab>=0.43.0

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/dclab#177]
If you encounter this issue, then there is a solution to it.

1. If you are working with dclab, Shape-Out 2, DCKit, or DCOR-Aid, you just need to install the latest version.
2. If you are working with other software, like HDFView, you need to make the [Zstandard](https://en.wikipedia.org/wiki/Zstd) compression algorithm available as an HDF5 plugin. If you have admin rights on your computer, you can do this by putting the corresponding library file into a pre-defined directory (which you might have to create):
 2.1. **Windows**: Extract [libh5zstd-windows.zip](https://github.com/ZELLMECHANIK-DRESDEN/dclab/files/8958343/libh5zstd-windows.zip) and put the *libh5zstd.dll* file in the directory `C:\\ProgramData\hdf5\lib\plugin`
 2.2. **Linux**: Extract [libh5zstd-linux.zip](https://github.com/ZELLMECHANIK-DRESDEN/dclab/files/8958357/libh5zstd-linux.zip) and put the *libh5zstd.so* file in the directory `/usr/local/hdf5/lib/plugin/`.
 2.3 **macOS**: Extract [libh5zstd-macos.zip](https://github.com/ZELLMECHANIK-DRESDEN/dclab/files/8958385/libh5zstd-macos.zip) and put the *libh5zstd.dylib* file in the directory `/usr/local/hdf5/lib/plugin/`.

Further reading:
- These libraries I downloaded from the 3.2.1 release of hdf5plugin https://pypi.org/project/hdf5plugin/
- https://portal.hdfgroup.org/display/HDF5/HDF5+Dynamically+Loaded+Filters

@ZELLMECHANIK-DRESDEN/collaborators

**Comment by PinkShnack** [comment]
FYI seems the above guide works for HDFView but not HDFViewApp. So make sure to download HDFView!
