### ISSUE TITLE
Hyperelastic Lookup Tables 

### ISSUE THREAD

**Issue by lucaswittwer** [ZELLMECHANIK-DRESDEN/dclab#188]
Integration of the two newly proposed LUTs for RT-DC based on a hyperelastic neo-Hookean material model for the cells and shear-thinning non-Newtonian fluid (e.g. 0.6% MC-PBS) in cylindrical and square channel geometries based on [1].

The two lookup tables have the identifiers
`HE-2D-FEM-22` for the cylindrical channel geometry with equivalence channel radius as in the current LUT [2]
`HE-3D-FEM-22`for the square channel geometry

For more details, see [1]

[1] L. D. Wittwer, F. Reichel, P. Müller, J. Guck, and S. Aland, “A New Hyperelastic Lookup Table for RT-DC,” arXiv [q-bio.QM], Aug. 26, 2022 [Online]. Available: http://arxiv.org/abs/2208.12552
[2] M. Mokbel et al., “Numerical Simulation of Real-Time Deformability Cytometry To Extract Cell Mechanical Properties,” ACS Biomat Sci & Eng, vol. 3, no. 11, pp. 2962–2973, Nov. 2017, doi: 10.1021/acsbiomaterials.6b00558. [Online]. Available: http://dx.doi.org/10.1021/acsbiomaterials.6b00558

**Comment by paulmueller** [comment]
The goal is to have a file like this one:

https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/master/dclab/features/emodulus/emodulus_lut_LE-2D-FEM-19.txt

I will extract the LUTs from these files:

https://figshare.com/articles/dataset/Hyperelastic_Lookup_Table_for_Real-Time_Deformability_Cytometry_RT-DC_/20630940?file=36862014
https://figshare.com/articles/dataset/Hyperelastic_Lookup_Table_for_Real-Time_Deformability_Cytometry_RT-DC_/20630940?file=36862020

**Comment by paulmueller** [comment]
In [aeecaf7](https://github.com/ZELLMECHANIK-DRESDEN/dclab/commit/aeecaf7b564fddb6b78bf773cd25ff07593e8bd5) I implemented the LUT and isoelastics retrieval recipe for HE-2D-FEM-22:
![HE-2D-FEM-22_extrapolation](https://user-images.githubusercontent.com/2853022/193762590-fc4f4479-2008-498c-8c16-5300a6c8c92d.png)
![HE-2D-FEM-22_LUT+isoel](https://user-images.githubusercontent.com/2853022/193762587-9a9e7678-1727-409b-b45e-440e60cbe099.png)

**Comment by paulmueller** [comment]
And here are the plots for HE-3D-FEM-22:

area_um-deform:

![HE-3D-FEM-22_area_1](https://user-images.githubusercontent.com/2853022/193991443-1906fa03-2a57-4413-bf0a-f68928fbb89f.png)
![HE-3D-FEM-22_area_2](https://user-images.githubusercontent.com/2853022/193991441-8a33395f-cdf6-4099-84d9-100dbce585f3.png)
![HE-3D-FEM-22_area_3](https://user-images.githubusercontent.com/2853022/193991436-169a290d-21b8-423d-affe-0b5a5c44b0ce.png)

volume-deform:

![HE-3D-FEM-22_volume_1](https://user-images.githubusercontent.com/2853022/194001018-bf3bc67c-9de4-4420-8f9d-36e6710b275e.png)
![HE-3D-FEM-22_volume_2](https://user-images.githubusercontent.com/2853022/194001016-edd0eff0-f383-482f-b36d-6aa6351d7550.png)
![HE-3D-FEM-22_volume_3](https://user-images.githubusercontent.com/2853022/194001014-a0c1f8a6-1cf9-4763-b930-27d960626c64.png)

**Comment by paulmueller** [comment]
New plots for the 2D model:

area:
![HE-2D-FEM-22_area_1](https://user-images.githubusercontent.com/2853022/194068782-2f3a4d8d-cbc3-4b0d-8312-9ea5764a43da.png)
![HE-2D-FEM-22_area_2](https://user-images.githubusercontent.com/2853022/194068803-fbff2e71-a285-46e9-a935-94bf87302076.png)
![HE-2D-FEM-22_area_3](https://user-images.githubusercontent.com/2853022/194068815-84a182b5-45fc-4092-a354-2afc87f538c7.png)

volume:
![HE-2D-FEM-22_volume_1](https://user-images.githubusercontent.com/2853022/194068865-314ba94d-38ac-4cb7-8b
![HE-2D-FEM-22_volume_2](https://user-images.githubusercontent.com/2853022/194068876-5aa3a12f-b4f4-46d0-9466-c52771774d2f.png)
9e-5bc45cb2f072.png)
![HE-2D-FEM-22_volume_3](https://user-images.githubusercontent.com/2853022/194068701-f23d503c-8a52-417f-9cb5-9b08e3afacf0.png)

**Comment by paulmueller** [comment]
New plots for 3D:

area:
![HE-3D-FEM-22_area_1](https://user-images.githubusercontent.com/2853022/194068978-95e90917-5e79-4809-a3da-ad5b5db1ce6f.png)
![HE-3D-FEM-22_area_2](https://user-images.githubusercontent.com/2853022/194068982-059126cb-e33c-4409-ace3-08554121ac65.png)
![HE-3D-FEM-22_area_3](https://user-images.githubusercontent.com/2853022/194068986-f04db6fa-9531-4f83-8af7-c8232571d711.png)

volume:
![HE-3D-FEM-22_volume_1](https://user-images.githubusercontent.com/2853022/194068989-d590032b-7b61-4dc5-abed-1ab896a20de3.png)
![HE-3D-FEM-22_volume_2](https://user-images.githubusercontent.com/2853022/194068992-4527249d-96e8-45ec-80fb-5f5203cd11fe.png)
![HE-3D-FEM-22_volume_3](https://user-images.githubusercontent.com/2853022/194068994-cf085f30-3a95-41e1-beb9-0d9429398b75.png)
