### ISSUE TITLE
Feature request: Batch conversion of .tdms data into .rtdc files

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/dclab#40]
Could we please implement a dclab function to batch process large amounts of measurements ( > 500) into the new data format? - This would be very useful and would speed up analysis tasks with older data.

I would suggest that one gives the function a source and a destination folder. It would then recreate the source folder structure in the destination with converted .rtdc files.

**Comment by paulmueller** [comment]
Yes, see #36. I added your request there.
