### ISSUE TITLE
Add ancillary feature "nevents"

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/dclab#44]
"nevents" (formerly) "ncells" is not anymore computed by ShapeIn.

See https://github.com/ZELLMECHANIK-DRESDEN/rtdc_hdf5/issues/11#issuecomment-381866324.

"nevents" can be computed by counting the number of events that have the same frame number.

**Comment by paulmueller** [comment]
@phidahl @chrherold
Please share with me the original code for determining the number of events in an image. 
There are no two events with the same frame number (The second event appears to not be present in the tdms files).
Is this computed from the fluorescence trace somehow or is an object detection algorithm applied to the image?

**Comment by phidahl** [comment]
The software that created the ncells column was not able to handle multiple events in one source frame. But to avoid wrong assignment of fluorescence peaks in cases with multiple cells detected in the source image, the ncells column was added. More recent versions of ShapeIn can detect multiple events per source image and have functionality to check correct peak to cell assignment.

It would be sufficient to show the column if it is present.

However we could think of using the frame number column to detect events from source images with multiple cells. But I’m not sure if this is really useful.

**Comment by paulmueller** [comment]
OK, won't implement it then.
