### ISSUE TITLE
Add ancillary feature "principal inertia ratio"

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/dclab#46]
Reference: https://github.com/ZELLMECHANIK-DRESDEN/dclab/pull/20
By @maikherbig:
> Inerita Ratio has no rotational invariance, which is especially a problem, if we want to use it for reservoir measurements. Rotational invariance is no problem in the channel since cells are aligned by the flow anyway, but the slow flow in the reservoir is not able to align all cells. The principal seond moment of area has rotational invariance. To compute it, the contour is rotated such that the second moment is maximal in x direction and minimal in y-direction.

The code for alignment is part of this commit: https://github.com/ZELLMECHANIK-DRESDEN/dclab/pull/20/commits/fd14c30c8891909632dacf27718e85b95a8a36ab

**Comment by paulmueller** [comment]
Here is the alignment code as text (to be on the safe side):

```python
        if align:                                 
            #get the orientation of the contour
            if mu1['mu02'] == mu1['mu20']:
                orientation = 0.5 * np.pi
            else:
                orientation = 0.5 * np.arctan(2 * mu1['mu11']/(mu1['mu02'] - mu1['mu20']))
            I_1 = abs(0.5 * (mu1['mu02'] + mu1['mu20']) + 0.5*(mu1['mu02'] - mu1['mu20']) * np.cos(2*orientation) + mu1['mu11'] * np.sin(2*orientation))  # x-axis tilted by alpha
            I_2 = abs(0.5 * (mu1['mu02'] + mu1['mu20']) - 0.5*(mu1['mu02'] - mu1['mu20']) * np.cos(2*orientation) - mu1['mu11'] * np.sin(2*orientation))  # y-axis tilted by alpha
            
            # If I_1 is bigger than I_2, the angle needs to be corrected by pi/2  
            # convention for arctan function is to take value between -pi/2 and pi/2
            if I_1 > I_2:
                orientation = (orientation + 0.5 * np.pi)     
            orientations[i] = orientation
            #Take the centroid if given or calculate if not given
            if get_pos_x:
                #calculate pos_x
                pos_x_i = mu1['m10']/mu1['m00']
            else:
                pos_x_i = pos_x[i]
                
            if get_pos_y:
                #calculate pos_y
                pos_y_i = mu1['m01']/mu1['m00']
            else:
                pos_y_i = pos_y[i]

            #remove the centroid (move the cell such that its centroid equla the origin)
            cont_i = cont[i].astype(float).reshape(cont[i].shape[0],2)
            cont_i[:,0] = cont_i[:,0]-pos_x_i
            cont_i[:,1] = cont_i[:,1]-pos_y_i
            #Rotate the contour
            rho = np.sqrt(cont_i[:,0]**2 + cont_i[:,1]**2) #get polarcoordinates
            phi = np.arctan2(cont_i[:,1], cont_i[:,0])
            phi = phi+orientation #rotate
            #transform back to cartesian coordinates
            cont_i[:,0] = rho * np.cos(phi)
            cont_i[:,1] = rho * np.sin(phi)

            #convert contour to OpenCV format
            cont_i = cont_i.astype(int).reshape(cont_i.shape[0],1,2)
    
            #get the moments of this rotated object
            hull = cv2.convexHull(cont_i, returnPoints=True)
            mu1 = cv2.moments(cont_i, False)
            mu2 = cv2.moments(hull, False)
        
            inertiaratio_principal_raw[i] = np.sqrt(mu1['mu20']/mu1['mu02'])
            inertiaratio_principal_hull[i] = np.sqrt(mu2['mu20']/mu2['mu02'])
```

**Comment by paulmueller** [comment]
TODO:
- [ ] ShapeOut: Make this feature available only in expert mode
- [ ] Implement alignment in https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/master/dclab/features/inert_ratio.py
- [ ] Add ancillary feature
- [ ] Add tests

**Comment by phidahl** [comment]
I talked to Christoph and we both think that `inertiaratio_principal_hull` would not be very useful. For clarity it would better be not displayed in ShapeOut.

**Comment by paulmueller** [comment]
We already agreed that it should only be visible in expert mode (see todo list above).

**Comment by paulmueller** [comment]
This is now implemented in the development version of dclab and can be tested with the latest ShapeOut build:
https://ci.appveyor.com/project/paulmueller/shapeout/build/1.0.946/job/gaa0tldqqi99wkl2

@maikherbig: Please let me know whether this is consistent with your implementation.
