### ISSUE TITLE
new ancillary feature: orientation

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/dclab#53]
Alongside #46, it might be interesting to also add the orientation (interval -PI/2 to +PI/2) relative to the channel axis. This might be useful for filtering.

Any comments @maikherbig @phidahl  @chrherold?

**Comment by phidahl** [comment]
Yes, that could be useful to filter out cell too close to channel walls.

**Comment by paulmueller** [comment]
I implemented this as `tilt`: "Absolute tilt of raw contour". Absolute, because it makes filtering easier (negative and positive orientation won't have to be filtered separately).
