### ISSUE TITLE
Opening and merging .rtdc files

### ISSUE THREAD

**Issue by maikherbig** [ZELLMECHANIK-DRESDEN/dclab#57]
I can't open .rtdc files and actually get the values/images/contours
I can't merge two .rtdc files.
Could you please provide  example code how to do this?
I attached two .rtdc files which I (exemplary
![m1_bg_102](https://user-images.githubusercontent.com/14074051/49315381-d1dabd00-f4ed-11e8-8336-81cfe8039b88.png)

![m2_bg_102](https://user-images.githubusercontent.com/14074051/49315382-d2735380-f4ed-11e8-825e-c7ea368f8371.png)

) would like to merge.

**Comment by paulmueller** [comment]
Have you read these sections of the documentation:
- https://dclab.readthedocs.io/en/stable/sec_getting_started.html#basic-usage
- https://dclab.readthedocs.io/en/stable/sec_av_notation.html
- https://dclab.readthedocs.io/en/stable/sec_av_rtdc_dataset.html#scripting-goodies

To get the first contour, you have to

```python
import dclab
ds = dclab.new_dataset("data/example.rtdc")
contour0 = ds["contour"][0]
```

Merging of rtdc files should be possible with https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/master/dclab/rtdc_dataset/write_hdf5.py#L135 using ``mode="append"``.

**Comment by paulmueller** [comment]
Have you managed to merge the files? Please let me know whether or not you need more help.

**Comment by paulmueller** [comment]
I doubt it, but I could have a look, if someone provided me with a broken file.

**Comment by paulmueller** [comment]
I had a look at the file. Fixing hdf5 files is currently not possible with the standard tools. 
This is the output of h5debug:

```
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 140543628659584:
  #000: ../../../src/H5F.c line 579 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: ../../../src/H5Fint.c line 1212 in H5F_open(): unable to read root group
    major: File accessibilty
    minor: Unable to open file
  #002: ../../../src/H5Groot.c line 241 in H5G_mkroot(): can't check if symbol table message exists
    major: Symbol table
    minor: Can't get value
  #003: ../../../src/H5Omessage.c line 889 in H5O_msg_exists(): unable to protect object header
    major: Object header
    minor: Unable to protect metadata
  #004: ../../../src/H5O.c line 1866 in H5O_protect(): unable to load object header chunk
    major: Object header
    minor: Unable to protect metadata
  #005: ../../../src/H5AC.c line 1351 in H5AC_protect(): H5C_protect() failed.
    major: Object cache
    minor: Unable to protect metadata
  #006: ../../../src/H5C.c line 3290 in H5C_protect(): can't load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #007: ../../../src/H5C.c line 8701 in H5C_load_entry(): Can't read image*
    major: Object cache
    minor: Read failed
  #008: ../../../src/H5Fio.c line 134 in H5F_block_read(): read through metadata accumulator failed
    major: Low-level I/O
    minor: Read failed
  #009: ../../../src/H5Faccum.c line 210 in H5F__accum_read(): driver read request failed
    major: Low-level I/O
    minor: Read failed
  #010: ../../../src/H5FDint.c line 213 in H5FD_read(): addr overflow, addr = 4168, size=104, eoa=2048
    major: Invalid arguments to routine
    minor: Address overflowed
cannot open file
HDF5: infinite loop closing library
      L,T_top,P,P,FD,E,SL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL
```

It looks like it would require a considerable amount of work to fix such files. Here are some relevant links:

- http://hdf-forum.184993.n3.nabble.com/HDF5-repair-tool-td4026552.html
- https://support.hdfgroup.org/products/hdf5_tools/#h5dist

In the meantime, I would suggest a different approach in Shape-In.

1. Store multiple ~100MB .rtdc files per measurement and merge them after the measurement. This is probably the easiest solution.

2. Work with `flush`, as @maikherbig suggested. This would however require more coding and it is unclear whether or not this could also result in corrupted files.

3. In Shape-In, make sure that the rtdc files are written to disk when an error occurs. Not sure though if this is as easy in C as it is in Python (@phidahl)?

**Comment by paulmueller** [comment]
@maikherbig @marketakub

dclab 0.12.0 introduces the command line script `dclab-join` which can be used to join a set of smaller datasets. You can also use it from within Python:

```python

from dclab import cli
cli.join(path_out="joined.rtdc", paths_in=["M1.rtdc", "M2.rtdc", "M3.rtdc"])
```

This also takes care of logs, meta data and indexing.

Cheers,
Paul
