### ISSUE TITLE
Overshoot in volume calculation in reservoir measurement for one particular sample

### ISSUE THREAD

**Issue by MartaUrb** [ZELLMECHANIK-DRESDEN/dclab#67]
### General information
- Operating System: Windows 7
- ShapeOut version: ShapeOut 0.9.5
- ShapeOut install: Windows 64bit installer

### Steps to reproduce the problem
1. Open Shapeout
2. Search for a dataset \guck_rtdc\experiments_16_17\20161213_Marta_DC_Vimentin\
3. Select reservoir measurement (M3) for sample "20161213_01_wt" (this is the problematic one) and one other sample for comparison "20161213_02_VimKO"
4. Plot area vs volume

### Data files
It is an old measurment so we have ".tdms" file

### Expected behavior
The volume values assigned to a fraction of cells in the M3 for the sample "20161213_01_wt" are off by 1-2 orders of magnitude. One can see it in the plot. It happens only for this particular reservoir measurement.
There is also the problem of contours not overlaying the cell images in the event image (indexing issue*)?
The contours, though, look quite decent and not huge - the values cannot be explained by this.
Could it be that there is a problem with assigning centroid?

*I have opened the tdms file and there are 4 entries for the first cells. I have deleted the first 3 and problem persists
(a copy of dataset with deleted first 3 rows in tdms files can be found here:
\guck_rtdc\Analysis\Marta\Vimentin\20161213_01_wt_inlet)

There is no error message

**Comment by paulmueller** [comment]
I have moved this issue to dclab, because in the end it fits better here. It will be fixed in dclab 0.14.4.

**Comment by paulmueller** [comment]
You can test it here: https://ci.appveyor.com/api/buildjobs/03ybj3vp7e40vmui/artifacts/.appveyor%2FOutput%2FShape-Out_0.9.5.post8_win_64bit_setup.exe

**Comment by MartaUrb** [comment]
Hi Paul. I just had a quick look and the volume calculation worked well with the 0.9.5post8 version of ShapeOut. Also, on the images the contours were fitting to the cells. Great fix!
