### ISSUE TITLE
Question: Adding user defined features

### ISSUE THREAD

**Issue by felix-r** [ZELLMECHANIK-DRESDEN/dclab#68]
I saw in the docs that you defined 10 user defined features. I don't know the function of these but I would like to add data that I computed from the dclab.dataset to the given dataset for further analysis. Is this possible? If yes, how?

**Comment by paulmueller** [comment]
I think the original function of these features was to test the computation of a new feature online. Let's say a user needs to read-out an additional sensor during the measurement (e.g. ambient pressure), then he could store this information in a user-defined feature. If this feature becomes an important feature, then we can talk about adding it as a new feature in dclab.

If you would like to use the userdef* features offline, you cannot use dclab directly, as dclab opens datasets read-only by default. However, you can open the .rtdc file in h5py and add the new feature:

```python
import dclab
import h5py
import numpy as np
import shutil

infile = "test.rtdc"
outfile = "out.rtdc"

# 1. copy original file
shutil.copy(infile, outfile)

# 2. get information for computing user-defined feature
with dclab.new_dataset(infile) as ds:
    userdef1 = np.sqrt(ds["deform"] * 2)

# 3. append user-defined feature
with h5py.File(outfile, mode="a") as h5:
    h5["events/userdef1"] = userdef1

# 4. verify that it worked
with dclab.new_dataset(outfile) as ds:
    assert "userdef1" in ds
```

Are you working with tdms files? Then you would have to convert them to the .rtdc format first, using

```python
from dclab.cli import tdms2rtdc

tdms2rtdc(path_tdms="test.tdms",
          path_rtdc="test.rtdc",
          compute_features=False,
          skip_initial_empty_image=True,
          verbose=False)
```

**Comment by felix-r** [comment]
Thank you. This answer is very helpful for what I want to do.

**Comment by paulmueller** [comment]
OK great, closing this one.
