### ISSUE TITLE
Disable Young's Modulus calculation for reservoir measurements

### ISSUE THREAD

**Issue by MartaUrb** [ZELLMECHANIK-DRESDEN/dclab#75]
### General information
- Windows 7 and 10
- ShapeOut 0.9.8 (and others)
- Windows 64bit 

### Steps to reproduce the problem
Load any measurement containing reservoir measurement, calculate Young's modulus and plot it.
 
### Expected behavior
No Young's modulus calculated for reservoir measurement 

### Actual behavior
Some very high Young's modulus values are assigned to the reservoir measurements

**Comment by paulmueller** [comment]
I moved this to dclab, because it only required changes here.

**Comment by MartaUrb** [comment]
Ok. Thanks for the info

**Comment by paulmueller** [comment]
You can test it here:

Shape-Out 1
https://ci.appveyor.com/api/buildjobs/vx43b6gec0440tx9/artifacts/.appveyor%2FOutput%2FShape-Out_1.0.3.post1_win_64bit_setup.exe

Shape-Out 2
https://ci.appveyor.com/api/buildjobs/7bwx9w1htlv1b3dq/artifacts/.appveyor%2FOutput%2FShape-Out_2.1.0.post3_win_64bit_setup.exe
