### ISSUE TITLE
dclab.new_dataset tries to load DCOR data set if local path is wrong

### ISSUE THREAD

**Issue by lucaswittwer** [ZELLMECHANIK-DRESDEN/dclab#81]
System: dclab-29.1, Python3 3.6.9, Ubuntu 18.04

Problem:
If the path to the local dataset in dclab.new_dataset is wrong, dclab seems to interpret the path as a URL and tries to load a DCOR dataset. This results in a unicode and socket timeout error which is missleading and makes debugging harder.

Testing if it is a path or an URL and throwing a "FileNotFoundError" exception or similar would make it easier  to debug...

Thanks!

**Comment by paulmueller** [comment]
Workaround is to always pass the path as ``pathlib.Path``.
