### ISSUE TITLE
Error for manual viscosity input in emodulus calculation

### ISSUE THREAD

**Issue by felix-r** [ZELLMECHANIK-DRESDEN/dclab#86]
When you want to compute the elastic modulus by manually setting a viscosity dclab throws an error. I do the following:

    ds = dclab.new_dataset(file)

    # emodulus computation
    ds.config["calculation"]["emodulus medium"] = 5.0 #ds.config["setup"]["medium"]
    ds.config["calculation"]["emodulus model"] = "elastic sphere"
    ds.config["calculation"]["emodulus temperature"] = None

    ds['emodulus']

Which raises:

```
ValueError                                Traceback (most recent call last)
<ipython-input-6-c4a88218be62> in <module>
     17 
     18 #     ds_filtered = dclab.new_dataset(ds)
---> 19     ds['emodulus']

~\AppData\Local\Continuum\anaconda3\lib\site-packages\dclab\rtdc_dataset\core.py in __getitem__(self, key)
    103             else:
    104                 # Compute new value
--> 105                 data = ancol[key].compute(self)
    106                 # Store computed value in `self._ancillaries`.
    107                 self._ancillaries[key] = (anhash, data)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\dclab\rtdc_dataset\ancillaries\ancillary_feature.py in compute(self, rtdc_ds)
    159             The computed data feature (read-only).
    160         """
--> 161         data = self.method(rtdc_ds)
    162         dsize = len(rtdc_ds) - len(data)
    163 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\dclab\rtdc_dataset\ancillaries\af_emodulus.py in compute_emodulus_known_media(mm)
     38     if medium not in features.emodulus.viscosity.KNOWN_MEDIA:
     39         raise ValueError("Only the following media are supported: {}".format(
---> 40                          features.emodulus.viscosity.KNOWN_MEDIA))
     41     # compute elastic modulus
     42     emod = features.emodulus.get_emodulus(

ValueError: Only the following media are supported: ['CellCarrier', 'CellCarrierB', 'water']

```

The problem is in `dclab\rtdc_dataset\ancillaries\af_emodulus.py in compute_emodulus_known_media(mm)` because there, no other medium than in `KNOWN_MEDIA` is allowed. This was tested with dclab 0.31.1. Would be nice to have a fix rather soon because the issue is a bit pressing for a collaborator. Thanks.

**Comment by paulmueller** [comment]
Thanks,

What happens if you remove the ``ds.config["calculation"]["emodulus temperature"] = None`` line (https://dclab.readthedocs.io/en/stable/sec_av_emodulus.html)?

If this fixes it, then the least I could do is to make the error message more verbose...

**Comment by felix-r** [comment]
It gives you the error, that for manual viscosity the temperature has to be set to `None`:

    ValueError: If `medium` is given in Pa*s, then `temperature` must be set to None!

Just found out that when you call the function directly you get a result:

```
In: dclab.features.emodulus.get_emodulus(area_um=ds['area_um'], deform=ds['deform'], volume=None, medium=5.0,
                 channel_width=20.0, flow_rate=0.16, px_um=0.34,
                 temperature=None, lut_data="FEM-2Daxis", copy=True)

Out: array([ 8.5822473 , 12.45498633, 13.77119096, ..., 14.82120115,
        7.89118643,  5.85645039])
```

It is just not implemented for the rtdc_dataset instance.

**Comment by paulmueller** [comment]
Try to set ``emodulus viscosity`` instead ``emodulus medium``:

``ds.config["calculation"]["emodulus viscosity"] = 5.0``

I will add a type check.

**Comment by felix-r** [comment]
Alright, this works. Thank you!
