### ISSUE TITLE
Young's Modulus Computation: Allow external LUT file

### ISSUE THREAD

**Issue by lucaswittwer** [ZELLMECHANIK-DRESDEN/dclab#88]
For the Young's Modulus computation based on new LUTs it would be nice to have a way to set the `emodulus model` to the path of the new LUT-file instead for example `"elastic sphere"`.

This way, testing out the influence of new LUTs is much easier and comparing the effect on measurements would use the base dclab-functionality

**Comment by paulmueller** [comment]
FYI: this caused a refactoring cascade with several deprecations. But this way it is easier now to add new LUTs to dclab: https://dclab.readthedocs.io/en/stable/sec_av_emodulus.html#external-lut
