### ISSUE TITLE
New Area Limit in the fem2lutiso_std.py Script

### ISSUE THREAD

**Issue by lucaswittwer** [ZELLMECHANIK-DRESDEN/dclab#90]
Description: 
The fem2lutiso_std.py crops all the 2DAxis LUTs to an area < 290um^2 (see the comment at [link](https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/bce6c30f238a654ce90664621aad195c3309e64e/scripts/fem2lutiso_std.py#L16)). This is/was due to the linear elastic LUT to have numerical instabilities for big cells as they are close to the equivalent channel walls. For the hyper-elastic LUTs, this is not the case any more as they relax. 

I suggest to update the script s.t. it is not only on the dimensionality of the underlying simulated data but on the identifier too, in the 2DAxis case, this will be `HL-2DAxis-FEM-20` and be part of the hdf5 file.

**Comment by paulmueller** [comment]
The affected line: https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/bce6c30f238a654ce90664621aad195c3309e64e/scripts/fem2lutiso_std.py#L195

These special cases really clutter the code. I am thinking about doing the following things:
- Edit the HDF5 file on figshare and add an identifier in the new version.
- Write separate Python scripts (plug-in like) for each LUT simulation dataset. Hopefully, only the current LUT will have such special cases.

**Comment by lucaswittwer** [comment]
I thought about updating the figshare data too and adding the identifier there. It would make everything more streamlined...

I like the plug-in approach!

 One thing we might want to consider is adding the fluid model to the identifier too, e.g. `N` for Newtonian Fluids, `NN` for non-Newtonian. The scaling law still holds based on the apparent viscosity in the channel. On the other hand, it would inflate the identifier and there might be even more sub-tags to add in the future. So keeping it as simple as possible at the moment is probably the better approach.

**Comment by paulmueller** [comment]
Regarding the fluid model: I would not add it to the identifier, because
A) All identifiers should have the same length :smile: 
B) There aren't so many datasets, that this could not be distinguished by the year :grin:
