### ISSUE TITLE
area_cvx feature - int or float?

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/dclab#96]
Hi @phidahl ,

@PinkShnack realized that the feature `area_cvx` is a float coming from Shape-In, but defined as int in dclab:
https://github.com/ZELLMECHANIK-DRESDEN/dclab/issues/93#issuecomment-783630429

Which one is correct?

**Comment by phidahl** [comment]
It's float because of the special way opencv counts pixels, there can be values with .5.
For simplicity the scalar features are all float in the hdf5 file which would also be true for shapelink.

**Comment by PinkShnack** [comment]
Should we then change the assertion in the tests for `"area_cvx"` as `float` to be consistent?

**Comment by paulmueller** [comment]
Yes, for the sake of clarity, we should change the dtype of `area_cvx` in that test.
